Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,37 +1,91 @@
-name: Upload Website
+
+name: Build, Scan, and Deploy to Staging
 
 on:
   push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+    branches:
+      - master # Trigger the workflow on push to the master branch
+
+  workflow_dispatch:
+
+permissions:
+  id-token: write
+  contents: read
 
 jobs:
-  build:
+  build-and-scan:
+    
+    name: Deploy to Staging
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+    - name: Checkout code
+      uses: actions/checkout@v2
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: '16'
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v1
 
+    - name: Set up docker build prereqs (QEMU)
+      uses: docker/setup-qemu-action@v3
 
-      - name: Install dependencies
-        run: npm install
+    - name: Configure AWS credentials
+      uses: aws-actions/configure-aws-credentials@v1
+      with:
+        aws-access-key-id: ${{ secrets.STG_AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.STG_AWS_SECRET_ACCESS_KEY }}
+        aws-region: ap-south-1
 
-      - name: Build app
-        run: npm run build
+    - name: Log in to Amazon ECR
+      id: login-ecr
+      uses: aws-actions/amazon-ecr-login@v1
 
-      - name: Upload to S3
-        uses: pravin1710/wqd@master  
-        with:
-          args: --acl public-read
-        env:
-          SOURCE_DIR: build/
-          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    - name: Build, tag image 
+      id: build-image
+      env:
+        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+        ECR_REPOSITORY: calendar-service
+        IMAGE_SHA: ${{ github.sha }} 
+      run: |
+        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_SHA .
+        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_SHA $ECR_REGISTRY/$ECR_REPOSITORY:latest
+
+    - name: Scan Docker Image with AWS Inspector
+      id: inspector
+      uses: aws-actions/vulnerability-scan-github-action-for-amazon-inspector@v1.1.1
+      with:
+        artifact_type: 'container'
+        artifact_path: ${{ env.ECR_REGISTRY }}/sales-activity-service:$IMAGE_SHA
+        display_vulnerability_findings: "enabled"
+        critical_threshold: 3
+        high_threshold: 10
+
+    - name: Upload Inspector scan results as artifacts
+      uses: actions/upload-artifact@v3
+      with:
+        name: Inspector Vulnerability Scan Artifacts
+        path: |
+          ${{ steps.inspector.outputs.inspector_scan_results }}
+          ${{ steps.inspector.outputs.inspector_scan_results_csv }}
+          ${{ steps.inspector.outputs.artifact_sbom }}
+          ${{ steps.inspector.outputs.inspector_scan_results_markdown }}
+
+    - name: Check vulnerability threshold
+      id: check-threshold
+      run: | 
+        echo "Vulnerability threshold check: ${{ steps.inspector.outputs.vulnerability_threshold_exceeded }}"
+    
+    - name: Fail if vulnerability threshold exceeded
+      if: ${{ steps.inspector.outputs.vulnerability_threshold_exceeded == '3' }}
+      run: |
+        echo "Vulnerability threshold exceeded. Failing the job."
+        exit 1
+
+    - name: Push image to Amazon ECR
+      if: ${{ steps.inspector.outputs.vulnerability_threshold_exceeded == '2' }}
+      run: |
+        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_SHA
+        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
+
+    - name: Deploy to ECS
+      run: |
+        aws ecs update-service --cluster Leadsigma-prod-cluster --service calendar-service --force-new-deployment
