Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -79,18 +79,20 @@ jobs:
     - name: Check vulnerability threshold
       id: check-threshold
       run: | 
-        RESULT=${{ steps.inspector.outputs.vulnerability_threshold_exceeded }}"
-        #STATUS=$?
-        echo "Vulnerability threshold check result is $RESULT"
-        #condition statement
-        if [[ $RESULT == 0 ]];then
-           echo "start deployment process using latest image "
-        else
-          echo "Newly Build docker images failed the threshold values: Start cleaup"
-          aws ecr batch-delete-image --repository-name calendar-service --image-ids imageTag=${{ github.sha }}
-          aws ecr batch-delete-image --repository-name calendar-service --image-ids imageTag=latest
-          exit 1
-        fi
+         chmod 0777 check.sh
+         ./check.sh
+        # RESULT=${{ steps.inspector.outputs.vulnerability_threshold_exceeded }}"
+        # #STATUS=$?
+        # echo "Vulnerability threshold check result is $RESULT"
+        # #condition statement
+        # if [[ $RESULT == 0 ]];then
+        #    echo "start deployment process using latest image "
+        # else
+        #   echo "Newly Build docker images failed the threshold values: Start cleaup"
+        #   aws ecr batch-delete-image --repository-name calendar-service --image-ids imageTag=${{ github.sha }}
+        #   aws ecr batch-delete-image --repository-name calendar-service --image-ids imageTag=latest
+        #   exit 1
+        # fi
           
         #echo "Vulnerability threshold check: ${{ steps.inspector.outputs.vulnerability_threshold_exceeded }}"
 
